version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*lint*"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore: "
