name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  type-check:
    name: Check Types
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run type:check

  build:
    name: Check Build
    needs: type-check
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run build
