name: Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  type-check:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run TypeScript compiler
        run: npm run type:check

  build:
    name: Check Build
    needs: type-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
