name: Format & Lint

on:
  push:
    branches: ["development", "main"]
  pull_request:
    branches: ["development", "main"]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Lint markdown files
        run: npm run lint:md

  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
