name: Format & Lint

on: [pull_request]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn format:check
      - name: Lint
        run: yarn lint
