name: Markdown

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-markdown:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Lint markdown files
        run: npm run lint:md
